[[redirects]]
  from = "/api/*"
  to = "https://my-finances-api.netlify.app/.netlify/functions/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/test"
  to = "https://isensee.nl"
  status = 200